var emojis = [
'chicken',
'goat',
'bowtie',
'smile',
'laughing',
'blush',
'smiley',
'relaxed',
'smirk',
'heart_eyes',
'kissing_heart',
'kissing_closed_eyes',
'flushed',
'relieved',
'satisfied',
'grin',
'wink',
'stuck_out_tongue_winking_eye',
'stuck_out_tongue_closed_eyes',
'grinning',
'kissing',
'kissing_smiling_eyes',
'stuck_out_tongue',
'sleeping',
'worried',
'frowning',
'anguished',
'open_mouth',
'grimacing',
'confused',
'hushed',
'expressionless',
'unamused',
'sweat_smile',
'sweat',
'disappointed_relieved',
'weary',
'pensive',
'disappointed',
'confounded',
'fearful',
'cold_sweat',
'persevere',
'cry',
'sob',
'joy',
'astonished',
'scream',
'neckbeard',
'tired_face',
'angry',
'rage',
'triumph',
'sleepy',
'yum',
'mask',
'sunglasses',
'dizzy_face',
'smiling_imp',
'neutral_face',
'no_mouth',
'innocent',
'alien',
'yellow_heart',
'blue_heart',
'purple_heart',
'heart',
'green_heart',
'broken_heart',
'heartbeat',
'heartpulse',
'two_hearts',
'revolving_hearts',
'cupid',
'sparkling_heart',
'sparkles',
'star',
'star2',
'dizzy',
'boom',
'collision',
'anger',
'exclamation',
'question',
'grey_exclamation',
'grey_question',
'zzz',
'dash',
'sweat_drops',
'notes',
'musical_note',
'fire',
'hankey',
'poop',
'shit',
'thumbsup',
'thumbsdown',
'ok_hand',
'punch',
'facepunch',
'fist',
'wave',
'hand',
'raised_hand',
'open_hands',
'point_up',
'point_down',
'point_left',
'point_right',
'raised_hands',
'pray',
'point_up_2',
'clap',
'muscle',
'metal',
'runner',
'running',
'couple',
'family',
'two_men_holding_hands',
'two_women_holding_hands',
'dancer',
'dancers',
'ok_woman',
'no_good',
'information_desk_person',
'raising_hand',
'bride_with_veil',
'person_with_pouting_face',
'person_frowning',
'bow',
'couplekiss',
'couple_with_heart',
'massage',
'haircut',
'nail_care',
'boy',
'girl',
'woman',
'man',
'baby',
'older_woman',
'older_man',
'person_with_blond_hair',
'man_with_gua_pi_mao',
'man_with_turban',
'construction_worker',
// 'cop',
'angel',
'princess',
'smiley_cat',
'smile_cat',
'heart_eyes_cat',
'kissing_cat',
'smirk_cat',
'scream_cat',
'crying_cat_face',
'joy_cat',
'pouting_cat',
'japanese_ogre',
'japanese_goblin',
'see_no_evil',
'hear_no_evil',
'speak_no_evil',
'guardsman',
'skull',
'feet',
'lips',
'kiss',
'droplet',
'ear',
'eyes',
'nose',
'tongue',
'love_letter',
'bust_in_silhouette',
'busts_in_silhouette',
'speech_balloon',
'thought_balloon',
];

function findMyText(needle) {
  var haystackText = document.getElementsByClassName("app-main")[0].innerHTML;
  var regexp = needle.join('|');
  var match = new RegExp(regexp, "ig");
  var replaced = "";
  replaced = haystackText.replace(match, function(matchedWord){
    return '<img src="https://afeld.github.io/emoji-css/emoji/' + matchedWord.toLowerCase() + '.png"/>';
  });
  document.getElementsByClassName("app-main")[0].innerHTML = replaced;
}

window.setTimeout(function() {
  console.log("running");
  emojis=emojis.map(function(emoji){
    return '\\b' + emoji;
  });
  debugger;
  findMyText(emojis);
}, 3000);



/*
replaceEmoji('feelsgood');
replaceEmoji('finnadie');
replaceEmoji('goberserk');
replaceEmoji('godmode');
replaceEmoji('hurtrealbad');
replaceEmoji('rage1');
replaceEmoji('rage2');
replaceEmoji('rage3');
replaceEmoji('rage4');
replaceEmoji('suspect');
replaceEmoji('trollface');
replaceEmoji('atur');
replaceEmoji('sunny');
replaceEmoji('umbrella');
replaceEmoji('cloud');
replaceEmoji('snowflake');
replaceEmoji('snowman');
replaceEmoji('zap');
replaceEmoji('cyclone');
replaceEmoji('foggy');
replaceEmoji('ocean');
replaceEmoji('cat');
replaceEmoji('dog');
replaceEmoji('mouse');
replaceEmoji('hamster');
replaceEmoji('rabbit');
replaceEmoji('wolf');
replaceEmoji('frog');
replaceEmoji('tiger');
replaceEmoji('koala');
replaceEmoji('bear');
replaceEmoji('pig');
replaceEmoji('pig_nose');
replaceEmoji('cow');
replaceEmoji('boar');
replaceEmoji('monkey_face');
replaceEmoji('monkey');
replaceEmoji('horse');
replaceEmoji('racehorse');
replaceEmoji('camel');
replaceEmoji('sheep');
replaceEmoji('elephant');
replaceEmoji('panda_face');
replaceEmoji('snake');
replaceEmoji('bird');
replaceEmoji('baby_chick');
replaceEmoji('hatched_chick');
replaceEmoji('hatching_chick');
replaceEmoji('chicken');
replaceEmoji('penguin');
replaceEmoji('turtle');
replaceEmoji('bug');
replaceEmoji('honeybee');
replaceEmoji('ant');
replaceEmoji('beetle');
replaceEmoji('snail');
replaceEmoji('octopus');
replaceEmoji('tropical_fish');
replaceEmoji('fish');
replaceEmoji('whale');
replaceEmoji('whale2');
replaceEmoji('dolphin');
replaceEmoji('cow2');
replaceEmoji('ram');
replaceEmoji('rat');
replaceEmoji('water_buffalo');
replaceEmoji('tiger2');
replaceEmoji('rabbit2');
replaceEmoji('dragon');
replaceEmoji('goat');
replaceEmoji('rooster');
replaceEmoji('dog2');
replaceEmoji('pig2');
replaceEmoji('mouse2');
replaceEmoji('ox');
replaceEmoji('dragon_face');
replaceEmoji('blowfish');
replaceEmoji('crocodile');
replaceEmoji('dromedary_camel');
replaceEmoji('leopard');
replaceEmoji('cat2');
replaceEmoji('poodle');
replaceEmoji('paw_prints');
replaceEmoji('bouquet');
replaceEmoji('cherry_blossom');
replaceEmoji('tulip');
replaceEmoji('four_leaf_clover');
replaceEmoji('rose');
replaceEmoji('sunflower');
replaceEmoji('hibiscus');
replaceEmoji('maple_leaf');
replaceEmoji('leaves');
replaceEmoji('fallen_leaf');
replaceEmoji('herb');
replaceEmoji('mushroom');
replaceEmoji('cactus');
replaceEmoji('palm_tree');
replaceEmoji('evergreen_tree');
replaceEmoji('deciduous_tree');
replaceEmoji('chestnut');
replaceEmoji('seedling');
replaceEmoji('blossom');
replaceEmoji('ear_of_rice');
replaceEmoji('shell');
replaceEmoji('globe_with_meridians');
replaceEmoji('sun_with_face');
replaceEmoji('full_moon_with_face');
replaceEmoji('new_moon_with_face');
replaceEmoji('new_moon');
replaceEmoji('waxing_crescent_moon');
replaceEmoji('first_quarter_moon');
replaceEmoji('waxing_gibbous_moon');
replaceEmoji('full_moon');
replaceEmoji('waning_gibbous_moon');
replaceEmoji('last_quarter_moon');
replaceEmoji('waning_crescent_moon');
replaceEmoji('last_quarter_moon_with_face');
replaceEmoji('first_quarter_moon_with_face');
replaceEmoji('crescent_moon');
replaceEmoji('earth_africa');
replaceEmoji('earth_americas');
replaceEmoji('earth_asia');
replaceEmoji('volcano');
replaceEmoji('milky_way');
replaceEmoji('partly_sunny');
replaceEmoji('octocat');
replaceEmoji('squirrel');
replaceEmoji('bject');
replaceEmoji('bamboo');
replaceEmoji('gift_heart');
replaceEmoji('dolls');
replaceEmoji('school_satchel');
replaceEmoji('mortar_board');
replaceEmoji('flags');
replaceEmoji('fireworks');
replaceEmoji('sparkler');
replaceEmoji('wind_chime');
replaceEmoji('rice_scene');
replaceEmoji('jack_o_lantern');
replaceEmoji('ghost');
replaceEmoji('santa');
replaceEmoji('christmas_tree');
replaceEmoji('gift');
replaceEmoji('bell');
replaceEmoji('no_bell');
replaceEmoji('tanabata_tree');
replaceEmoji('tada');
replaceEmoji('confetti_ball');
replaceEmoji('balloon');
replaceEmoji('crystal_ball');
replaceEmoji('cd');
replaceEmoji('dvd');
replaceEmoji('floppy_disk');
replaceEmoji('camera');
replaceEmoji('video_camera');
replaceEmoji('movie_camera');
replaceEmoji('computer');
replaceEmoji('tv');
replaceEmoji('iphone');
replaceEmoji('phone');
replaceEmoji('telephone');
replaceEmoji('telephone_receiver');
replaceEmoji('pager');
replaceEmoji('fax');
replaceEmoji('minidisc');
replaceEmoji('vhs');
replaceEmoji('sound');
replaceEmoji('speaker');
replaceEmoji('mute');
replaceEmoji('loudspeaker');
replaceEmoji('mega');
replaceEmoji('hourglass');
replaceEmoji('hourglass_flowing_sand');
replaceEmoji('alarm_clock');
replaceEmoji('watch');
replaceEmoji('radio');
replaceEmoji('satellite');
replaceEmoji('loop');
replaceEmoji('mag');
replaceEmoji('mag_right');
replaceEmoji('unlock');
replaceEmoji('lock');
replaceEmoji('lock_with_ink_pen');
replaceEmoji('closed_lock_with_key');
replaceEmoji('key');
replaceEmoji('bulb');
replaceEmoji('flashlight');
replaceEmoji('high_brightness');
replaceEmoji('low_brightness');
replaceEmoji('electric_plug');
replaceEmoji('battery');
replaceEmoji('calling');
replaceEmoji('email');
replaceEmoji('mailbox');
replaceEmoji('postbox');
replaceEmoji('bath');
replaceEmoji('bathtub');
replaceEmoji('shower');
replaceEmoji('toilet');
replaceEmoji('wrench');
replaceEmoji('nut_and_bolt');
replaceEmoji('hammer');
replaceEmoji('seat');
replaceEmoji('moneybag');
replaceEmoji('yen');
replaceEmoji('dollar');
replaceEmoji('pound');
replaceEmoji('euro');
replaceEmoji('credit_card');
replaceEmoji('money_with_wings');
replaceEmoji('e-mail');
replaceEmoji('inbox_tray');
replaceEmoji('outbox_tray');
replaceEmoji('envelope');
replaceEmoji('incoming_envelope');
replaceEmoji('postal_horn');
replaceEmoji('mailbox_closed');
replaceEmoji('mailbox_with_mail');
replaceEmoji('mailbox_with_no_mail');
replaceEmoji('package');
replaceEmoji('door');
replaceEmoji('smoking');
replaceEmoji('bomb');
replaceEmoji('gun');
replaceEmoji('hocho');
replaceEmoji('pill');
replaceEmoji('syringe');
replaceEmoji('page_facing_up');
replaceEmoji('page_with_curl');
replaceEmoji('bookmark_tabs');
replaceEmoji('bar_chart');
replaceEmoji('chart_with_upwards_trend');
replaceEmoji('chart_with_downwards_trend');
replaceEmoji('scroll');
replaceEmoji('clipboard');
replaceEmoji('calendar');
replaceEmoji('date');
replaceEmoji('card_index');
replaceEmoji('file_folder');
replaceEmoji('open_file_folder');
replaceEmoji('scissors');
replaceEmoji('pushpin');
replaceEmoji('paperclip');
replaceEmoji('black_nib');
replaceEmoji('pencil2');
replaceEmoji('straight_ruler');
replaceEmoji('triangular_ruler');
replaceEmoji('closed_book');
replaceEmoji('green_book');
replaceEmoji('blue_book');
replaceEmoji('orange_book');
replaceEmoji('notebook');
replaceEmoji('notebook_with_decorative_cover');
replaceEmoji('ledger');
replaceEmoji('books');
replaceEmoji('bookmark');
replaceEmoji('name_badge');
replaceEmoji('microscope');
replaceEmoji('telescope');
replaceEmoji('newspaper');
replaceEmoji('football');
replaceEmoji('basketball');
replaceEmoji('soccer');
replaceEmoji('baseball');
replaceEmoji('tennis');
replaceEmoji('8ball');
replaceEmoji('rugby_football');
replaceEmoji('bowling');
replaceEmoji('golf');
replaceEmoji('mountain_bicyclist');
replaceEmoji('bicyclist');
replaceEmoji('horse_racing');
replaceEmoji('snowboarder');
replaceEmoji('swimmer');
replaceEmoji('surfer');
replaceEmoji('ski');
replaceEmoji('spades');
replaceEmoji('hearts');
replaceEmoji('clubs');
replaceEmoji('diamonds');
replaceEmoji('gem');
replaceEmoji('ring');
replaceEmoji('trophy');
replaceEmoji('musical_score');
replaceEmoji('musical_keyboard');
replaceEmoji('violin');
replaceEmoji('space_invader');
replaceEmoji('video_game');
replaceEmoji('black_joker');
replaceEmoji('flower_playing_cards');
replaceEmoji('game_die');
replaceEmoji('dart');
replaceEmoji('mahjong');
replaceEmoji('clapper');
replaceEmoji('memo');
replaceEmoji('pencil');
replaceEmoji('book');
replaceEmoji('art');
replaceEmoji('microphone');
replaceEmoji('headphones');
replaceEmoji('trumpet');
replaceEmoji('saxophone');
replaceEmoji('guitar');
replaceEmoji('shoe');
replaceEmoji('sandal');
replaceEmoji('high_heel');
replaceEmoji('lipstick');
replaceEmoji('boot');
replaceEmoji('shirt');
replaceEmoji('tshirt');
replaceEmoji('necktie');
replaceEmoji('womans_clothes');
replaceEmoji('dress');
replaceEmoji('running_shirt_with_sash');
replaceEmoji('jeans');
replaceEmoji('kimono');
replaceEmoji('bikini');
replaceEmoji('ribbon');
replaceEmoji('tophat');
replaceEmoji('crown');
replaceEmoji('womans_hat');
replaceEmoji('mans_shoe');
replaceEmoji('closed_umbrella');
replaceEmoji('briefcase');
replaceEmoji('handbag');
replaceEmoji('pouch');
replaceEmoji('purse');
replaceEmoji('eyeglasses');
replaceEmoji('fishing_pole_and_fish');
replaceEmoji('coffee');
replaceEmoji('tea');
replaceEmoji('sake');
replaceEmoji('baby_bottle');
replaceEmoji('beer');
replaceEmoji('beers');
replaceEmoji('cocktail');
replaceEmoji('tropical_drink');
replaceEmoji('wine_glass');
replaceEmoji('fork_and_knife');
replaceEmoji('pizza');
replaceEmoji('hamburger');
replaceEmoji('fries');
replaceEmoji('poultry_leg');
replaceEmoji('meat_on_bone');
replaceEmoji('spaghetti');
replaceEmoji('curry');
replaceEmoji('fried_shrimp');
replaceEmoji('bento');
replaceEmoji('sushi');
replaceEmoji('fish_cake');
replaceEmoji('rice_ball');
replaceEmoji('rice_cracker');
replaceEmoji('rice');
replaceEmoji('ramen');
replaceEmoji('stew');
replaceEmoji('oden');
replaceEmoji('dango');
replaceEmoji('egg');
replaceEmoji('bread');
replaceEmoji('doughnut');
replaceEmoji('custard');
replaceEmoji('icecream');
replaceEmoji('ice_cream');
replaceEmoji('shaved_ice');
replaceEmoji('birthday');
replaceEmoji('cake');
replaceEmoji('cookie');
replaceEmoji('chocolate_bar');
replaceEmoji('candy');
replaceEmoji('lollipop');
replaceEmoji('honey_pot');
replaceEmoji('apple');
replaceEmoji('green_apple');
replaceEmoji('tangerine');
replaceEmoji('lemon');
replaceEmoji('cherries');
replaceEmoji('grapes');
replaceEmoji('watermelon');
replaceEmoji('strawberry');
replaceEmoji('peach');
replaceEmoji('melon');
replaceEmoji('banana');
replaceEmoji('pear');
replaceEmoji('pineapple');
replaceEmoji('sweet_potato');
replaceEmoji('eggplant');
replaceEmoji('tomato');
replaceEmoji('corn');
replaceEmoji('lace');
replaceEmoji('house');
replaceEmoji('house_with_garden');
replaceEmoji('school');
replaceEmoji('office');
replaceEmoji('post_office');
replaceEmoji('hospital');
replaceEmoji('bank');
replaceEmoji('convenience_store');
replaceEmoji('love_hotel');
replaceEmoji('hotel');
replaceEmoji('wedding');
replaceEmoji('church');
replaceEmoji('department_store');
replaceEmoji('european_post_office');
replaceEmoji('city_sunrise');
replaceEmoji('city_sunset');
replaceEmoji('japanese_castle');
replaceEmoji('european_castle');
replaceEmoji('tent');
replaceEmoji('factory');
replaceEmoji('tokyo_tower');
replaceEmoji('japan');
replaceEmoji('mount_fuji');
replaceEmoji('sunrise_over_mountains');
replaceEmoji('sunrise');
replaceEmoji('stars');
replaceEmoji('statue_of_liberty');
replaceEmoji('bridge_at_night');
replaceEmoji('carousel_horse');
replaceEmoji('rainbow');
replaceEmoji('ferris_wheel');
replaceEmoji('fountain');
replaceEmoji('roller_coaster');
replaceEmoji('ship');
replaceEmoji('speedboat');
replaceEmoji('boat');
replaceEmoji('sailboat');
replaceEmoji('rowboat');
replaceEmoji('anchor');
replaceEmoji('rocket');
replaceEmoji('airplane');
replaceEmoji('helicopter');
replaceEmoji('steam_locomotive');
replaceEmoji('tram');
replaceEmoji('mountain_railway');
replaceEmoji('bike');
replaceEmoji('aerial_tramway');
replaceEmoji('suspension_railway');
replaceEmoji('mountain_cableway');
replaceEmoji('tractor');
replaceEmoji('blue_car');
replaceEmoji('oncoming_automobile');
replaceEmoji('car');
replaceEmoji('red_car');
replaceEmoji('taxi');
replaceEmoji('oncoming_taxi');
replaceEmoji('articulated_lorry');
replaceEmoji('bus');
replaceEmoji('oncoming_bus');
replaceEmoji('rotating_light');
replaceEmoji('police_car');
replaceEmoji('oncoming_police_car');
replaceEmoji('fire_engine');
replaceEmoji('ambulance');
replaceEmoji('minibus');
replaceEmoji('truck');
replaceEmoji('train');
replaceEmoji('station');
replaceEmoji('train2');
replaceEmoji('bullettrain_front');
replaceEmoji('bullettrain_side');
replaceEmoji('light_rail');
replaceEmoji('monorail');
replaceEmoji('railway_car');
replaceEmoji('trolleybus');
replaceEmoji('ticket');
replaceEmoji('fuelpump');
replaceEmoji('vertical_traffic_light');
replaceEmoji('traffic_light');
replaceEmoji('warning');
replaceEmoji('construction');
replaceEmoji('beginner');
replaceEmoji('atm');
replaceEmoji('slot_machine');
replaceEmoji('busstop');
replaceEmoji('barber');
replaceEmoji('hotsprings');
replaceEmoji('checkered_flag');
replaceEmoji('crossed_flags');
replaceEmoji('izakaya_lantern');
replaceEmoji('moyai');
replaceEmoji('circus_tent');
replaceEmoji('performing_arts');
replaceEmoji('round_pushpin');
replaceEmoji('triangular_flag_on_post');
replaceEmoji('jp');
replaceEmoji('kr');
replaceEmoji('cn');
replaceEmoji('us');
replaceEmoji('fr');
replaceEmoji('es');
replaceEmoji('it');
replaceEmoji('ru');
replaceEmoji('gb');
replaceEmoji('uk');
replaceEmoji('de');
replaceEmoji('ymbol');
replaceEmoji('one');
replaceEmoji('two');
replaceEmoji('three');
replaceEmoji('four');
replaceEmoji('five');
replaceEmoji('six');
replaceEmoji('seven');
replaceEmoji('eight');
replaceEmoji('nine');
replaceEmoji('keycap_ten');
replaceEmoji('1234');
replaceEmoji('zero');
replaceEmoji('hash');
replaceEmoji('symbols');
replaceEmoji('arrow_backward');
replaceEmoji('arrow_down');
replaceEmoji('arrow_forward');
replaceEmoji('arrow_left');
replaceEmoji('capital_abcd');
replaceEmoji('abcd');
replaceEmoji('abc');
replaceEmoji('arrow_lower_left');
replaceEmoji('arrow_lower_right');
replaceEmoji('arrow_right');
replaceEmoji('arrow_up');
replaceEmoji('arrow_upper_left');
replaceEmoji('arrow_upper_right');
replaceEmoji('arrow_double_down');
replaceEmoji('arrow_double_up');
replaceEmoji('arrow_down_small');
replaceEmoji('arrow_heading_down');
replaceEmoji('arrow_heading_up');
replaceEmoji('leftwards_arrow_with_hook');
replaceEmoji('arrow_right_hook');
replaceEmoji('left_right_arrow');
replaceEmoji('arrow_up_down');
replaceEmoji('arrow_up_small');
replaceEmoji('arrows_clockwise');
replaceEmoji('arrows_counterclockwise');
replaceEmoji('rewind');
replaceEmoji('fast_forward');
replaceEmoji('information_source');
replaceEmoji('ok');
replaceEmoji('twisted_rightwards_arrows');
replaceEmoji('repeat');
replaceEmoji('repeat_one');
replaceEmoji('new');
replaceEmoji('top');
replaceEmoji('up');
replaceEmoji('cool');
replaceEmoji('free');
replaceEmoji('ng');
replaceEmoji('cinema');
replaceEmoji('koko');
replaceEmoji('signal_strength');
replaceEmoji('u5272');
replaceEmoji('u5408');
replaceEmoji('u55b6');
replaceEmoji('u6307');
replaceEmoji('u6708');
replaceEmoji('u6709');
replaceEmoji('u6e80');
replaceEmoji('u7121');
replaceEmoji('u7533');
replaceEmoji('u7a7a');
replaceEmoji('u7981');
replaceEmoji('sa');
replaceEmoji('restroom');
replaceEmoji('mens');
replaceEmoji('womens');
replaceEmoji('baby_symbol');
replaceEmoji('no_smoking');
replaceEmoji('parking');
replaceEmoji('wheelchair');
replaceEmoji('metro');
replaceEmoji('baggage_claim');
replaceEmoji('accept');
replaceEmoji('wc');
replaceEmoji('potable_water');
replaceEmoji('put_litter_in_its_place');
replaceEmoji('secret');
replaceEmoji('congratulations');
replaceEmoji('m');
replaceEmoji('passport_control');
replaceEmoji('left_luggage');
replaceEmoji('customs');
replaceEmoji('ideograph_advantage');
replaceEmoji('cl');
replaceEmoji('sos');
replaceEmoji('id');
replaceEmoji('no_entry_sign');
replaceEmoji('underage');
replaceEmoji('no_mobile_phones');
replaceEmoji('do_not_litter');
replaceEmoji('non-potable_water');
replaceEmoji('no_bicycles');
replaceEmoji('no_pedestrians');
replaceEmoji('children_crossing');
replaceEmoji('no_entry');
replaceEmoji('eight_spoked_asterisk');
replaceEmoji('sparkle');
replaceEmoji('eight_pointed_black_star');
replaceEmoji('heart_decoration');
replaceEmoji('vs');
replaceEmoji('vibration_mode');
replaceEmoji('mobile_phone_off');
replaceEmoji('chart');
replaceEmoji('currency_exchange');
replaceEmoji('aries');
replaceEmoji('taurus');
replaceEmoji('gemini');
replaceEmoji('cancer');
replaceEmoji('leo');
replaceEmoji('virgo');
replaceEmoji('libra');
replaceEmoji('scorpius');
replaceEmoji('sagittarius');
replaceEmoji('capricorn');
replaceEmoji('aquarius');
replaceEmoji('pisces');
replaceEmoji('ophiuchus');
replaceEmoji('six_pointed_star');
replaceEmoji('negative_squared_cross_mark');
replaceEmoji('a');
replaceEmoji('b');
replaceEmoji('ab');
replaceEmoji('o2');
replaceEmoji('diamond_shape_with_a_dot_inside');
replaceEmoji('recycle');
replaceEmoji('end');
replaceEmoji('back');
replaceEmoji('on');
replaceEmoji('soon');
replaceEmoji('clock1');
replaceEmoji('clock130');
replaceEmoji('clock10');
replaceEmoji('clock1030');
replaceEmoji('clock11');
replaceEmoji('clock1130');
replaceEmoji('clock12');
replaceEmoji('clock1230');
replaceEmoji('clock2');
replaceEmoji('clock230');
replaceEmoji('clock3');
replaceEmoji('clock330');
replaceEmoji('clock4');
replaceEmoji('clock430');
replaceEmoji('clock5');
replaceEmoji('clock530');
replaceEmoji('clock6');
replaceEmoji('clock630');
replaceEmoji('clock7');
replaceEmoji('clock730');
replaceEmoji('clock8');
replaceEmoji('clock830');
replaceEmoji('clock9');
replaceEmoji('clock930');
replaceEmoji('heavy_dollar_sign');
replaceEmoji('copyright');
replaceEmoji('registered');
replaceEmoji('tm');
replaceEmoji('x');
replaceEmoji('heavy_exclamation_mark');
replaceEmoji('bangbang');
replaceEmoji('interrobang');
replaceEmoji('o');
replaceEmoji('heavy_multiplication_x');
replaceEmoji('heavy_plus_sign');
replaceEmoji('heavy_minus_sign');
replaceEmoji('heavy_division_sign');
replaceEmoji('white_flower');
replaceEmoji('100');
replaceEmoji('heavy_check_mark');
replaceEmoji('ballot_box_with_check');
replaceEmoji('radio_button');
replaceEmoji('link');
replaceEmoji('curly_loop');
replaceEmoji('wavy_dash');
replaceEmoji('part_alternation_mark');
replaceEmoji('trident');
replaceEmoji('black_small_square');
replaceEmoji('white_small_square');
replaceEmoji('black_medium_small_square');
replaceEmoji('white_medium_small_square');
replaceEmoji('black_medium_square');
replaceEmoji('white_medium_square');
replaceEmoji('black_large_square');
replaceEmoji('white_large_square');
replaceEmoji('white_check_mark');
replaceEmoji('black_square_button');
replaceEmoji('white_square_button');
replaceEmoji('black_circle');
replaceEmoji('white_circle');
replaceEmoji('red_circle');
replaceEmoji('large_blue_circle');
replaceEmoji('large_blue_diamond');
replaceEmoji('large_orange_diamond');
replaceEmoji('small_blue_diamond');
replaceEmoji('small_orange_diamond');
replaceEmoji('small_red_triangle');
replaceEmoji('small_red_triangle_down');
replaceEmoji('shipit');
*/
